### ISSUE TITLE
Private key in repository?

### ISSUE THREAD

**Issue by djhoese** [davidbrochart/xtrude#1]
Is this a private key in the git history? This should probably be removed, right?

https://github.com/davidbrochart/xtrude/blob/main/examples/cert.pem

**Comment by davidbrochart** [comment]
Yes, thanks!

**Comment by djhoese** [comment]
You'll want to follow these instructions to remove it from the git history: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Otherwise anyone can just go back through the history and steal the key. People and bots do it all the time with github search.

**Comment by davidbrochart** [comment]
Thanks, it was just an auto-signed certificate, so I think it's fine.
